### ISSUE TITLE
ModuleNotFoundError: No module named "keras"

### ISSUE THREAD

**Issue by Twixtfanatic** [likeaj6/alphazero-hex#1]
My OS is Linux Mint 18.1 with MATE. I used git clone to download the files. I have python 3.6.0 from Continuum Analytics. When I typed in python3 sl_bootstrap.py I got the error ModuleNotFoundError: No module named "keras" I got the same error from python3 Hex.py

Is there a problem with the files, or am I doing something wrong? TIA

**Comment by likeaj6** [comment]
Hi there,

please see https://keras.io for installation instructions. Keras is a frequently used dependency for machine learning, so I suggest familiarizing yourself with the library!
